
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE sp_GetProfilePermissionsByIdEndpoint
	@IdEndpoint VARCHAR(36)
AS
BEGIN
	SET NOCOUNT ON;
	
	DECLARE @Endpoint NVARCHAR(100) = (SELECT TOP 1 Path FROM Endpoints WHERE IdEndpoint = @IdEndpoint);
	DECLARE @Permissions AS TABLE
	(
		IdPermission VARCHAR(36) NOT NULL,
		IdProfile VARCHAR(36) NOT NULL,
		Profile VARCHAR(50) NOT NULL,
		IdEndpoint VARCHAR(36) NOT NULL,
		Endpoint NVARCHAR(100) NOT NULL,
		Active BIT NOT NULL
	);

	SELECT * FROM @Permissions ORDER BY Profile;
END
GO
